### PR TITLE
Fix problems menu button

### PR DESCRIPTION
**Pull request by djsime1**

### CODE REVIEW

**Comment by LennyPenny** [comment]
thx!

**Comment by djsime1** [comment]
1. I guess VSCode's remote repos don't sign commits;
2. What are your thoughts on a redux update to make plugin management better than the current key-value tree? I'd be glad to author it.

**Comment by LennyPenny** [comment]
always open for reasonable improvement 
what are some of the problems of the current system has and how do you intent to solve them? 

please open an issue for this topic tho :)

**Comment by djsime1** [comment]
I'll open an issue about how I think things can be improved/extended unless you want to chat them out on Steam or Discord. ([links on my site](https://dj.je))

**Pull request merged**
