### PR TITLE
Add installation instructions

### PR DESCRIPTION
**Pull request by LennyPenny**

### CODE REVIEW

**Comment by SwadicalRag** [comment]
mysogyny

honestly this is what keeps minorities and women out of programming

**Comment by LennyPenny** [comment]
Yes github should add "women only" repos that require you to set your gender spectrum to mostly female on github

**Comment by SwadicalRag** [comment]
@meepdarknessmeep @moat7 thoughts?

**Comment by Kefta** [comment]
Every minority should be accurately represented in these white-dominated repositories.

**Pull request merged**
